CONFIG_I2S=y
CONFIG_AUDIO=y
CONFIG_AUDIO_CODEC=y
CONFIG_I2S_ESP32_TX_BLOCK_COUNT=8
CONFIG_I2S_ESP32_RX_BLOCK_COUNT=8
CONFIG_LOG=y

# Buttons not available on this board
CONFIG_TOGGLE_ECHO_EFFECT_SW0=n
CONFIG_STOP_START_STREAMS_SW1=n

# MCLK = 256 * 44100
CONFIG_I2S_MCLK_FREQUENCY=11289600
CONFIG_I2C=y
CONFIG_APP_OUTPUT_VOLUME=50
CONFIG_APP_INPUT_GAIN_DB=6
